# Generated by Django 5.1.4 on 2024-12-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geminimodel",
            name="base",
        ),
        migrations.RemoveField(
            model_name="geminimodel",
            name="header",
        ),
    ]
