# Generated by Django 5.1.4 on 2024-12-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_alter_geminimodel_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geminimodel",
            name="type",
            field=models.CharField(max_length=20),
        ),
    ]
