# Generated by Django 5.1.4 on 2024-12-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_alter_geminimodel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geminimodel",
            name="language_message",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="geminimodel",
            name="message",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="geminimodel",
            name="type",
            field=models.CharField(
                choices=[("validate", ""), ("translate", "")], max_length=10
            ),
        ),
    ]
